/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is the hub up (no auth) */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send one event or a batch of up to 500 */
        post: operations["post_events_api_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/cursor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Highest seq the hub has for this device */
        get: operations["get_cursor_api_v1_devices__device_id__cursor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pair/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Show a new pairing code (hub computer only) */
        post: operations["pair_start_api_v1_pair_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pair/qr.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** QR code for the active pairing code (hub computer only) */
        get: operations["pair_qr_api_v1_pair_qr_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pair/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trade a pairing code for a token */
        post: operations["pair_claim_api_v1_pair_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paired devices, including revoked ones */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a device's token (hub computer only); its data stays */
        delete: operations["revoke_device_api_v1_devices__device_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One day's lanes: devices, calendar, sleep, meals */
        get: operations["get_timeline_api_v1_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories, and the apps seen recently */
        get: operations["list_categories_api_v1_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the category of an app or site */
        put: operations["put_category_api_v1_categories__key__put"];
        post?: never;
        /** Remove a category override */
        delete: operations["delete_category_api_v1_categories__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The local model server: reachable, model, tool calling
         * @description Always 200: when the model can't be used, `reachable` or `tool_calling` says so and `error` explains.
         */
        get: operations["ai_status_api_v1_ai_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/story": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A short story of one day, every number checked */
        get: operations["get_story_api_v1_story_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask about your day: answered from your data through tool calls
         * @description 503 `ai_unavailable` when the local model can't be reached (unlike /story, there is no answer without it).
         */
        post: operations["post_ask_api_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiStatus */
        AiStatus: {
            /** Base Url */
            base_url: string;
            /** Model */
            model: string | null;
            /** Reachable */
            reachable: boolean;
            /** Tool Calling */
            tool_calling: boolean | null;
            /** Models */
            models: string[];
            /** Error */
            error: string | null;
        };
        /** Answer */
        Answer: {
            /** Answer */
            answer: string;
            /**
             * Facts Used
             * @description Every number in the answer matches one of these.
             */
            facts_used: components["schemas"]["FactOut"][];
            /** Tools Called */
            tools_called: string[];
            /** @description A small series the dashboard can draw, when a tool returned one. */
            chart: components["schemas"]["Chart"] | null;
            /**
             * Model
             * @description The local model that wrote it; null when the facts are shown instead.
             */
            model: string | null;
            /**
             * Fallback
             * @description True when the model's answer failed the number check twice: the facts are shown.
             */
            fallback: boolean;
            /**
             * Declined
             * @description True when the question was not about your day.
             */
            declined: boolean;
            /**
             * Reason
             * @description Why the facts are shown instead of an answer.
             */
            reason: string | null;
        };
        /** AppCategory */
        AppCategory: {
            /**
             * Key
             * @description PUT /categories/{key} sets this app's category.
             */
            key: string;
            /**
             * App
             * @description The name to show: the app name, or the app id or domain when there is none.
             */
            app: string;
            /** App Id */
            app_id: string | null;
            /** Kind */
            kind: string;
            /** Category */
            category: string;
            /**
             * Source
             * @enum {string}
             */
            source: "user" | "ai" | "builtin" | "collector" | "default";
            /**
             * Override
             * @description The override that decided (user or ai); DELETE it to undo.
             */
            override: string | null;
            /**
             * Events
             * @description Events for this app in the last 30 days (for sorting).
             */
            events: number;
        };
        /** AskIn */
        AskIn: {
            /**
             * Question
             * @description An empty one gets 400.
             */
            question: string;
            /**
             * Tz
             * @description IANA time zone, e.g. America/Toronto; default: the hub's
             */
            tz?: string | null;
        };
        /** CalendarEntry */
        CalendarEntry: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Title */
            title: string | null;
            /** All Day */
            all_day: boolean;
            /** Device Id */
            device_id: string;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "social" | "video" | "work" | "study" | "comms" | "games" | "health" | "other";
        /** CategoryChoice */
        CategoryChoice: {
            category: components["schemas"]["Category"];
        };
        /** CategoryList */
        CategoryList: {
            /** Categories */
            categories: string[];
            /** Apps */
            apps: components["schemas"]["AppCategory"][];
            /** Overrides */
            overrides: components["schemas"]["OverrideOut"][];
        };
        /** Chart */
        Chart: {
            /**
             * Kind
             * @description bar
             */
            kind: string;
            /** Title */
            title: string;
            /** Unit */
            unit: string;
            /** Points */
            points: components["schemas"]["ChartPoint"][];
        };
        /** ChartPoint */
        ChartPoint: {
            /** Label */
            label: string;
            /** Value */
            value: number;
        };
        /** Cursor */
        Cursor: {
            /** Device Id */
            device_id: string;
            /** Last Seq */
            last_seq: number | null;
        };
        /** DeviceInfo */
        DeviceInfo: {
            /** Device Id */
            device_id: string;
            /** Name */
            name: string;
            /** Device Type */
            device_type: string;
            /** Paired At */
            paired_at: string;
            /** Last Seen */
            last_seen: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Last Seq */
            last_seq: number | null;
            /** Event Count */
            event_count: number;
            /**
             * Events 24H
             * @description Events that started in the last 24 hours.
             */
            events_24h: number;
        };
        /** DeviceList */
        DeviceList: {
            /** Devices */
            devices: components["schemas"]["DeviceInfo"][];
        };
        /** FactOut */
        FactOut: {
            /** Label */
            label: string;
            /** Value */
            value: number | string;
            /** Unit */
            unit: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Profile */
            profile: string;
            /** Version */
            version: string;
        };
        /**
         * IngestResult
         * @description Response of POST /api/v1/events.
         */
        IngestResult: {
            /**
             * Accepted
             * @description New events stored by this request.
             */
            accepted: number;
            /**
             * Replaced
             * @description Stored events updated through their external_id.
             * @default 0
             */
            replaced: number;
            /**
             * Duplicates
             * @description Events already stored, ignored.
             */
            duplicates: number;
            /** Rejected */
            rejected?: components["schemas"]["RejectedEvent"][];
            /**
             * Last Seq
             * @description Highest seq stored for this device, or null.
             */
            last_seq?: number | null;
            nudge?: components["schemas"]["Nudge"] | null;
        };
        /** Lane */
        Lane: {
            /** Device Id */
            device_id: string;
            /** Device Type */
            device_type: string;
            /** Name */
            name: string;
            /**
             * Counted
             * @description False for browser-extension lanes, whose time is inside the desktop lane.
             */
            counted: boolean;
            /** Seconds */
            seconds: number;
            /** Minutes */
            minutes: number;
            /** Sessions */
            sessions: components["schemas"]["TimelineSession"][];
        };
        /** MealEntry */
        MealEntry: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Items */
            items: string[] | null;
            /** Text */
            text: string | null;
            /** Meal Type */
            meal_type: string | null;
            /** Device Id */
            device_id: string;
        };
        /** Meta */
        Meta: {
            /**
             * Unit
             * @default minutes
             * @constant
             */
            unit: "minutes";
            range: components["schemas"]["TimeRange"];
            /**
             * Source
             * @enum {string}
             */
            source: "real" | "seed" | "mixed";
            /** Estimated */
            estimated: boolean;
        };
        /**
         * Nudge
         * @description A gentle, timely prompt returned to the device that sent the triggering event (DT-43).
         */
        Nudge: {
            /** Rule */
            rule: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OverrideOut */
        OverrideOut: {
            /** Key */
            key: string;
            /** Category */
            category: string;
            /** Source */
            source: string;
            /** Updated At */
            updated_at: string;
        };
        /** PairClaim */
        PairClaim: {
            /** Code */
            code: string;
            /** Device Name */
            device_name: string;
            /**
             * Device Type
             * @enum {string}
             */
            device_type: "windows" | "macos" | "android" | "ios" | "browser" | "viewer";
        };
        /** PairClaimed */
        PairClaimed: {
            /** Device Id */
            device_id: string;
            /**
             * Device Type
             * @enum {string}
             */
            device_type: "windows" | "macos" | "android" | "ios" | "browser" | "viewer";
            /** Name */
            name: string;
            /**
             * Token
             * @description Shown once. Send it as Authorization: Bearer <token>.
             */
            token: string;
            /** Profile */
            profile: string;
        };
        /** PairStarted */
        PairStarted: {
            /** Code */
            code: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Url
             * @description The hub address for the QR code (its LAN IP, which every phone can reach), or null when this computer has no LAN address right now.
             */
            url: string | null;
            /**
             * Urls
             * @description Every address phones can use, LAN first, then Tailscale on shared-dev.
             */
            urls: string[];
            /**
             * Mdns Url
             * @description The .local address, when mDNS is on.
             */
            mdns_url: string | null;
            /** Qr */
            qr: string | null;
        };
        /**
         * RejectedEvent
         * @description One event the hub refused.
         *
         *     `invalid` and `wrong_device`: the collector drops it (resending would fail the same way).
         *     `seq_conflict`: the seq was already used for a different event (numbering restarted, for example after
         *     a reinstall); the collector renumbers its unsynced events after last_seq and sends them again.
         */
        RejectedEvent: {
            /** Index */
            index: number;
            /**
             * Code
             * @default invalid
             * @enum {string}
             */
            code: "invalid" | "wrong_device" | "seq_conflict";
            /** Seq */
            seq?: number | null;
            /** External Id */
            external_id?: string | null;
            /** Reason */
            reason: string;
        };
        /** SleepEntry */
        SleepEntry: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Minutes */
            minutes: number;
            /** Stage */
            stage: string | null;
            /** Estimated */
            estimated: boolean;
            /** Device Id */
            device_id: string;
        };
        /** Story */
        Story: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Tz */
            tz: string;
            /** Story */
            story: string;
            /**
             * Facts Used
             * @description Every number in the story matches one of these.
             */
            facts_used: components["schemas"]["FactOut"][];
            /**
             * Model
             * @description The local model that wrote it; null for the template story.
             */
            model: string | null;
            /** Cached */
            cached: boolean;
            /**
             * Fallback
             * @description True when the template story was used (model away, or unusable twice).
             */
            fallback: boolean;
            /**
             * Reason
             * @description Why the template story was used.
             */
            reason: string | null;
            /**
             * In Progress
             * @description True while the day is not over: the story is of the day so far.
             */
            in_progress: boolean;
        };
        /** TimeRange */
        TimeRange: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Tz */
            tz: string;
        };
        /** Timeline */
        Timeline: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Tz */
            tz: string;
            /** Lanes */
            lanes: components["schemas"]["Lane"][];
            /** Calendar */
            calendar: components["schemas"]["CalendarEntry"][];
            /** Sleep */
            sleep: components["schemas"]["SleepEntry"][];
            /** Meals */
            meals: components["schemas"]["MealEntry"][];
            totals: components["schemas"]["Totals"];
            meta: components["schemas"]["Meta"];
        };
        /** TimelineSession */
        TimelineSession: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Seconds */
            seconds: number;
            /** Minutes */
            minutes: number;
            /** App */
            app: string | null;
            /** App Id */
            app_id: string | null;
            /** Title */
            title: string | null;
            /**
             * Category
             * @description One of the categories in GET /categories; 'other' when unknown.
             */
            category: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "app" | "web";
            /**
             * Estimated
             * @description True when the end was inferred (an iPhone open with no close).
             */
            estimated: boolean;
        };
        /** Totals */
        Totals: {
            /**
             * Seconds
             * @description Screen time per counted device, added up. Exactly the sum of the lanes.
             */
            seconds: number;
            /** Minutes */
            minutes: number;
            /** By Device Seconds */
            by_device_seconds: {
                [key: string]: number;
            };
            /**
             * By Device
             * @description Minutes per counted device (rounded for display).
             */
            by_device: {
                [key: string]: number;
            };
            /**
             * Any Screen Seconds
             * @description Time at least one screen was in use (overlaps counted once).
             */
            any_screen_seconds: number;
            /** Any Screen Minutes */
            any_screen_minutes: number;
            /**
             * Sleep Seconds
             * @description Sleep that ended this day; overlapping stages and copies counted once.
             */
            sleep_seconds: number;
            /** Sleep Minutes */
            sleep_minutes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    post_events_api_v1_events_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cursor_api_v1_devices__device_id__cursor_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cursor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_start_api_v1_pair_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairStarted"];
                };
            };
        };
    };
    pair_qr_api_v1_pair_qr_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
        };
    };
    pair_claim_api_v1_pair_claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairClaim"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairClaimed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_device_api_v1_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeline_api_v1_timeline_get: {
        parameters: {
            query?: {
                /** @description YYYY-MM-DD; default: today in tz */
                date?: string | null;
                /** @description IANA time zone, e.g. America/Toronto; default: the hub's */
                tz?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_category_api_v1_categories__key__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description An app id, app name or web domain (slashes allowed). */
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryChoice"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_v1_categories__key__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description An app id, app name or web domain (slashes allowed). */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_status_api_v1_ai_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_api_v1_story_get: {
        parameters: {
            query?: {
                /** @description YYYY-MM-DD; default: today in tz */
                date?: string | null;
                /** @description IANA time zone, e.g. America/Toronto; default: the hub's */
                tz?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_ask_api_v1_ask_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
